name: NEXUS PRIME CORE

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # كل 30 دقيقة

jobs:
  nexus:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt
      - run: python watchdog.py
